modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="music_electronic"
version="1.6.2"
displayName="Music Electronic"
credits="NCS, TrapNation and GabrielDja"
displayURL="https://gabrieldjalayer.wixsite.com/gabrieldja-gaming-yt"
logoFile="logo.png"
authors="GabrielDja [ 2020 - 2022 ]"
description='''
Add lots of NCS and TrapNation music to Minecraft!!!
'''

[[dependencies.music_electronic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




